export const actionTypes = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    GET_CATEGORIES: 'GET_CATEGORIES',
    SET_CATEGORIES: 'SET_CATEGORIES',
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    SET_SHOPPING_CART: 'SET_SHOPPING_CART',
    GET_SHOPPING_CART: 'GET_SHOPPING_CART',
    SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER',
    SEARCH_PRODUCT: 'SEARCH_PRODUCT',
    SET_FILTER: 'SET_FILTER',
    GET_PRODUCT: 'GET_PRODUCT',
    SET_PRODUCT: 'SET_PRODUCT'
}